/**
 * Generates lib/build/ds-icon.generated.ts — the Shopify (Liquid) theme's icon
 * system: a `snippets/ds-icon.liquid` renderer + matching CSS. Maps both
 * semantic names AND legacy emoji to the same animated inline SVGs used by the
 * React themes (so old merchant data keeps working while going emoji-free).
 *
 * Run: node scripts/gen-ds-icon.mjs
 */
import { readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

// Load the shared inner-SVG map (name -> markup with zi-* classes).
const dataSrc = readFileSync(resolve('components/icons/animated/data.generated.ts'), 'utf8')
const json = dataSrc.slice(dataSrc.indexOf('{'), dataSrc.lastIndexOf('}') + 1)
const SVG = JSON.parse(json)

const SW = 'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"'
const wrap = (inner) => `<svg viewBox="0 0 24 24" ${SW}>${inner}</svg>`

/** canonical -> Liquid `when` triggers (names + legacy emoji). */
const GROUPS = {
  shipping:   ['truck','shipping','delivery','courier','free-shipping','🚚'],
  secure:     ['shield','secure','safe','safety','protection','trust','🛡️','🛡'],
  lock:       ['lock','encryption','ssl','🔒'],
  returns:    ['returns','return','refund','exchange','↩️','🔁'],
  check:      ['check','verified','guarantee','warranty','done','✅','✔️','✓'],
  chat:       ['chat','support','message','help','contact','💬'],
  star:       ['star','rated','rating','reviews','⭐','⭐️','★'],
  heart:      ['heart','love','care-love','💛','❤️','🖤'],
  gift:       ['gift','giftcard','🎁'],
  package:    ['package','parcel','product','box','📦'],
  boxes:      ['boxes','inventory','stock'],
  bolt:       ['bolt','zap','fast','instant','quick','speed','⚡'],
  sparkles:   ['sparkles','sparkle','new','premium','magic','✨','✦'],
  leaf:       ['leaf','eco','organic','natural','sustainable','green','🌿'],
  sprout:     ['sprout','farm','plant','🌱'],
  water:      ['water','waterproof','hydration','💧'],
  battery:    ['battery','rechargeable','usb','wireless','🔋'],
  tools:      ['tools','durable','quality-material','build','🛠️','🛠'],
  care:       ['care','comfort','soft','ergonomic','🤲'],
  feather:    ['feather','light','lightweight','compact','portable','🪶'],
  award:      ['award','quality','editors','certified','🏆'],
  trophy:     ['trophy','best','bestseller','winner','🥇'],
  clock:      ['clock','24-7','always-open','time','⏰'],
  timer:      ['timer','fast-delivery','⏱️'],
  phone:      ['phone','call','📞'],
  mail:       ['mail','email','newsletter','✉️','📧'],
  card:       ['card','credit-card','payment','pay','💳'],
  coins:      ['coins','cashback','🪙'],
  cash:       ['cash','money','money-back','💵'],
  tag:        ['tag','price','pricing','label','🏷️'],
  discount:   ['discount','sale','percent','offer','deal','%'],
  recycle:    ['recycle','recycled','biodegradable','♻️'],
  flame:      ['flame','fire','hot','trending','grill','bbq','🔥'],
  rocket:     ['rocket','launch','boost','🚀'],
  users:      ['users','community','team','members','👥'],
  user:       ['user','account','profile','👤'],
  calendar:   ['calendar','booking','schedule','appointment','📅'],
  thumbsup:   ['thumbs-up','reliable','satisfaction','👍'],
  coffee:     ['coffee','cafe','espresso','☕'],
  cart:       ['cart','shopping-cart','basket','🛒'],
  bag:        ['shopping-bag','bag','boutique','🛍️','🛍'],
  truckfast:  [], // reserved
}

// canonical name in GROUPS -> data.generated key (some differ)
const KEYMAP = { secure:'secure', thumbsup:'thumbs-up', bag:'shopping-bag', cart:'cart', flame:'grill', users:'community' }

function innerFor(canonical) {
  const key = KEYMAP[canonical] || canonical
  return SVG[key]
}

let cases = ''
for (const [canonical, triggers] of Object.entries(GROUPS)) {
  if (!triggers.length) continue
  const inner = innerFor(canonical)
  if (!inner) { console.error('no svg for', canonical); continue }
  const when = triggers.map((t) => `'${t.replace(/'/g, "\\'")}'`).join(', ')
  cases += `  {%- when ${when} -%}${wrap(inner)}\n`
}
const fallback = wrap(SVG['sparkles'])

const snippet = `{%- comment -%} AUTO-GENERATED by scripts/gen-ds-icon.mjs — do not edit. {%- endcomment -%}
{%- assign zn = name | downcase | strip -%}
<span class="zi ds-ico">
{%- case zn -%}
${cases}  {%- else -%}${fallback}
{%- endcase -%}
</span>`

// CSS — same keyframes as app/globals.css, self-hover + card hover.
const css = `
/* Zenya animated icons */
.zi{display:inline-flex;line-height:0}
.zi svg{width:1em;height:1em;overflow:visible}
.ds-ico svg{width:100%;height:100%}
.zi svg *{transform-box:view-box;transform-origin:12px 12px}
@keyframes zi-swing{0%,100%{transform:rotate(0)}18%{transform:rotate(-13deg)}38%{transform:rotate(10deg)}56%{transform:rotate(-8deg)}72%{transform:rotate(6deg)}86%{transform:rotate(-3deg)}}
@keyframes zi-spin{to{transform:rotate(360deg)}}
@keyframes zi-flip{to{transform:rotate(180deg)}}
@keyframes zi-beat{0%,100%{transform:scale(1)}25%{transform:scale(1.18)}45%{transform:scale(.94)}70%{transform:scale(1.12)}}
@keyframes zi-pulse{0%,100%{transform:scale(1)}50%{transform:scale(1.12)}}
@keyframes zi-pop{0%,100%{transform:scale(1)}45%{transform:scale(1.22)}}
@keyframes zi-popspin{0%,100%{transform:rotate(0) scale(1)}50%{transform:rotate(72deg) scale(1.2)}}
@keyframes zi-tilt{0%,100%{transform:rotate(0)}35%{transform:rotate(-7deg)}70%{transform:rotate(5deg)}}
@keyframes zi-sway{0%,100%{transform:rotate(0)}25%{transform:rotate(-8deg)}55%{transform:rotate(6deg)}80%{transform:rotate(-4deg)}}
@keyframes zi-wobble{0%,100%{transform:rotate(0)}20%{transform:rotate(-6deg) scale(1.05)}60%{transform:rotate(5deg)}}
@keyframes zi-shake{0%,100%{transform:rotate(0)}20%{transform:rotate(-11deg)}40%{transform:rotate(9deg)}60%{transform:rotate(-7deg)}80%{transform:rotate(5deg)}}
@keyframes zi-wiggle{0%,100%{transform:translate(0,0)}25%{transform:translate(-2px,2px)}55%{transform:translate(2px,-1px)}80%{transform:translate(-1px,1px)}}
@keyframes zi-nudge{0%,100%{transform:translateX(0)}30%{transform:translateX(-1.5px)}65%{transform:translateX(2px)}}
@keyframes zi-slide{0%,100%{transform:translateX(0)}50%{transform:translateX(3.5px)}}
@keyframes zi-fly{0%,100%{transform:translate(0,0)}50%{transform:translate(3px,-3px)}}
@keyframes zi-jump{0%,100%{transform:translateY(0)}40%{transform:translateY(-3px)}70%{transform:translateY(1px)}}
@keyframes zi-bob{0%,100%{transform:translateY(0)}50%{transform:translateY(-2px)}}
@keyframes zi-wave{0%,100%{transform:rotate(0)}25%{transform:rotate(6deg)}75%{transform:rotate(-6deg)}}
@keyframes zi-flash{0%,100%{transform:scale(1);opacity:1}40%{transform:scale(1.15);opacity:.5}}
@keyframes zi-flicker{0%,100%{transform:scale(1) rotate(0);opacity:1}30%{transform:scale(1.08) rotate(-4deg);opacity:.75}60%{transform:scale(.96) rotate(3deg);opacity:1}}
@keyframes zi-lift{0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-1.5px) scale(1.22)}}
@keyframes zi-twinkle{0%{transform:scale(.6);opacity:.4}60%{transform:scale(1.3);opacity:1}100%{transform:scale(1);opacity:1}}
@keyframes zi-draw{from{stroke-dashoffset:1}to{stroke-dashoffset:0}}
.zi-draw{stroke-dasharray:1;stroke-dashoffset:0}
.zi:hover .zi-swing,[class$="__item"]:hover .zi-swing,[class$="__card"]:hover .zi-swing{animation:zi-swing .9s ease-in-out}
.zi:hover .zi-spin,[class$="__item"]:hover .zi-spin,[class$="__card"]:hover .zi-spin{animation:zi-spin .7s cubic-bezier(.4,0,.2,1)}
.zi:hover .zi-flip{animation:zi-flip .6s cubic-bezier(.4,0,.2,1)}
.zi:hover .zi-beat,[class$="__item"]:hover .zi-beat,[class$="__card"]:hover .zi-beat{animation:zi-beat .7s ease-in-out}
.zi:hover .zi-pulse{animation:zi-pulse .8s ease-in-out}
.zi:hover .zi-pop,[class$="__item"]:hover .zi-pop,[class$="__card"]:hover .zi-pop{animation:zi-pop .5s cubic-bezier(.2,1.4,.4,1)}
.zi:hover .zi-popspin,[class$="__item"]:hover .zi-popspin,[class$="__card"]:hover .zi-popspin{animation:zi-popspin .7s ease-in-out}
.zi:hover .zi-tilt{animation:zi-tilt .8s ease-in-out}
.zi:hover .zi-sway{animation:zi-sway 1s ease-in-out}
.zi:hover .zi-wobble{animation:zi-wobble .7s ease-in-out}
.zi:hover .zi-shake{animation:zi-shake .8s ease-in-out}
.zi:hover .zi-wiggle{animation:zi-wiggle .7s ease-in-out}
.zi:hover .zi-nudge,[class$="__item"]:hover .zi-nudge,[class$="__card"]:hover .zi-nudge{animation:zi-nudge .7s ease-in-out}
.zi:hover .zi-slide{animation:zi-slide .6s ease-in-out}
.zi:hover .zi-fly,[class$="__item"]:hover .zi-fly,[class$="__card"]:hover .zi-fly{animation:zi-fly .7s ease-in-out}
.zi:hover .zi-jump{animation:zi-jump .6s ease-in-out}
.zi:hover .zi-bob,[class$="__item"]:hover .zi-bob,[class$="__card"]:hover .zi-bob{animation:zi-bob .5s ease-in-out}
.zi:hover .zi-bob2{animation:zi-bob .5s ease-in-out .08s}
.zi:hover .zi-wave{animation:zi-wave .7s ease-in-out}
.zi:hover .zi-flash{animation:zi-flash .6s ease-in-out}
.zi:hover .zi-flicker{animation:zi-flicker .7s ease-in-out}
.zi:hover .zi-lift,[class$="__item"]:hover .zi-lift,[class$="__card"]:hover .zi-lift{animation:zi-lift .6s ease-in-out}
.zi:hover .zi-draw,[class$="__item"]:hover .zi-draw,[class$="__card"]:hover .zi-draw{animation:zi-draw .55s ease-in-out}
.zi:hover .zi-twinkle,[class$="__item"]:hover .zi-twinkle,[class$="__card"]:hover .zi-twinkle{animation:zi-twinkle .6s ease-in-out}
.zi:hover .zi-twinkle2{animation:zi-twinkle .6s ease-in-out .1s}
.zi:hover .zi-twinkle3{animation:zi-twinkle .6s ease-in-out .18s}
@media (prefers-reduced-motion:reduce){.zi *{animation:none !important}}
`.trim()

const ts = `// AUTO-GENERATED by scripts/gen-ds-icon.mjs — do not edit by hand.
/* eslint-disable */
export function dsIconSnippet(): string {
  return ${JSON.stringify(snippet)}
}
export const DS_ICON_CSS = ${JSON.stringify('\n' + css + '\n')}
`
const dest = resolve('lib/build/ds-icon.generated.ts')
writeFileSync(dest, ts)
console.log('wrote', dest, '— cases:', Object.values(GROUPS).filter(g=>g.length).length)
