-- Human-readable identifiers alongside the immutable UUID primary keys.
--
-- Motivation: browsing Supabase Studio was painful — every row keyed on a
-- 36-char UUID, no at-a-glance way to tell users/themes/purchases apart.
--
-- Changes:
--   1. profiles.handle  — URL-safe username derived from email; unique;
--      auto-assigned by BEFORE INSERT trigger for every new signup.
--   2. themes/purchases/domain_purchases/hosting_subscriptions each get
--      display_no (bigint identity) — a sequential "#42" pointer.
--   3. Two friendly views: admin_users_overview + admin_themes_overview,
--      accessible to service_role only, ordered by number so browsing is
--      trivial. These do NOT replace the underlying tables — the UUIDs
--      remain the source of truth for FKs, RLS, and auth.
--
-- Safety: every column is additive. No existing UUID, FK, index, RLS
-- policy, or auth.uid() reference is touched. Rolling this back is a
-- straightforward "drop column".

-- ────────────────────────────────────────────────────────────────────────
-- 1. profiles.handle
-- ────────────────────────────────────────────────────────────────────────

alter table public.profiles
  add column if not exists handle text;

-- Handle generator. Strips the email local-part to lowercase alnum. Two
-- users with the same email prefix would collide — the trigger dedups by
-- appending the user's member_no. Falls back to 'user' + member_no when
-- email is missing/unusable so no row is ever left without a handle.
create or replace function public.generate_handle_base(p_email text)
returns text
language sql
immutable
as $$
  select case
    when coalesce(p_email, '') = '' then 'user'
    when length(regexp_replace(lower(split_part(p_email, '@', 1)), '[^a-z0-9]', '', 'g')) < 2
      then 'user'
    else regexp_replace(lower(split_part(p_email, '@', 1)), '[^a-z0-9]', '', 'g')
  end;
$$;

-- BEFORE INSERT trigger — auto-assign a unique handle if none was passed.
-- Runs AFTER handle_new_user (which inserts email), so email is set.
create or replace function public.assign_profile_handle()
returns trigger
language plpgsql
security definer
set search_path = 'public', 'pg_temp'
as $$
declare
  base text;
  candidate text;
  n int := 0;
begin
  if new.handle is not null and new.handle <> '' then
    return new;
  end if;
  base := public.generate_handle_base(new.email);
  candidate := base;
  -- Cheap loop: for the first few tries append n, then fall back to
  -- '<base>-<member_no>' which is guaranteed unique (member_no is unique).
  while exists(select 1 from public.profiles where handle = candidate and id <> new.id) loop
    n := n + 1;
    if n > 5 then
      candidate := base || '-' || coalesce(new.member_no, 0)::text;
      exit;
    end if;
    candidate := base || n::text;
  end loop;
  new.handle := candidate;
  return new;
end;
$$;

drop trigger if exists profiles_assign_handle on public.profiles;
create trigger profiles_assign_handle
  before insert on public.profiles
  for each row execute function public.assign_profile_handle();

-- Backfill in member_no order so the "first" user gets the cleanest handle.
-- Any collisions cascade into a numeric suffix, then a member_no fallback.
do $$
declare
  r record;
  base text;
  candidate text;
  n int;
begin
  for r in
    select id, email, member_no
      from public.profiles
     where handle is null
     order by member_no asc nulls last, created_at asc
  loop
    base := public.generate_handle_base(r.email);
    candidate := base;
    n := 0;
    while exists(select 1 from public.profiles where handle = candidate and id <> r.id) loop
      n := n + 1;
      if n > 5 then
        candidate := base || '-' || coalesce(r.member_no, 0)::text;
        exit;
      end if;
      candidate := base || n::text;
    end loop;
    update public.profiles set handle = candidate where id = r.id;
  end loop;
end $$;

alter table public.profiles
  alter column handle set not null;

do $$
begin
  if not exists(
    select 1 from pg_constraint where conname = 'profiles_handle_key'
  ) then
    alter table public.profiles add constraint profiles_handle_key unique (handle);
  end if;
end $$;

-- ────────────────────────────────────────────────────────────────────────
-- 2. Sequential display_no on the other browsable tables
-- ────────────────────────────────────────────────────────────────────────

alter table public.themes
  add column if not exists display_no bigint generated by default as identity;
create unique index if not exists themes_display_no_key on public.themes(display_no);

alter table public.purchases
  add column if not exists display_no bigint generated by default as identity;
create unique index if not exists purchases_display_no_key on public.purchases(display_no);

alter table public.domain_purchases
  add column if not exists display_no bigint generated by default as identity;
create unique index if not exists domain_purchases_display_no_key on public.domain_purchases(display_no);

alter table public.hosting_subscriptions
  add column if not exists display_no bigint generated by default as identity;
create unique index if not exists hosting_subscriptions_display_no_key on public.hosting_subscriptions(display_no);

-- ────────────────────────────────────────────────────────────────────────
-- 3. Overview views — for one-click Supabase Studio browsing.
--     No UUIDs in the primary columns; UUIDs kept as trailing "id" for
--     when you need to join out to the raw tables.
-- ────────────────────────────────────────────────────────────────────────

drop view if exists public.admin_users_overview;
create view public.admin_users_overview
with (security_invoker = true) as
select
  p.member_no                                    as "#",
  p.handle                                       as "handle",
  coalesce(p.full_name, split_part(p.email, '@', 1)) as "name",
  p.email                                        as "email",
  p.plan                                         as "plan",
  p.is_pro                                       as "pro",
  p.has_hosting                                  as "hosting",
  p.trial_themes_used || '/' || p.trial_themes_limit as "trial",
  p.pro_purchased_at                             as "paid_at",
  p.last_seen_at                                 as "last_seen",
  p.created_at                                   as "joined",
  p.id                                           as "user_uuid"
from public.profiles p
order by p.member_no asc;

comment on view public.admin_users_overview is
  'Human-readable users list — # + handle + email + tier — ordered by member_no. '
  'UUID kept as trailing column for cross-table lookups. Founder browsing view.';

drop view if exists public.admin_themes_overview;
create view public.admin_themes_overview
with (security_invoker = true) as
select
  t.display_no                                   as "#",
  p.member_no                                    as "user_#",
  p.handle                                       as "user",
  t.product_name                                 as "name",
  t.template_type                                as "template",
  case
    when t.is_published and t.slug is not null then 'live · /s/' || t.slug
    when t.template_type in ('one_product','storefront','collective') then 'shopify export'
    else 'draft'
  end                                            as "status",
  t.view_count                                   as "views",
  t.created_at                                   as "created",
  t.id                                           as "theme_uuid"
from public.themes t
left join public.profiles p on p.id = t.user_id
order by t.display_no desc;

comment on view public.admin_themes_overview is
  'Human-readable themes list — # + owner handle + name + status. Newest first.';

-- Grant read on the overview views to authenticated (RLS on the underlying
-- profiles/themes tables still governs what each user sees — service_role
-- sees everything, users only see their own).
grant select on public.admin_users_overview   to authenticated, service_role;
grant select on public.admin_themes_overview  to authenticated, service_role;
